### ISSUE TITLE
Cover from Local Image?

### ISSUE THREAD

**Issue by Zottelchen** [dfface/xml2epub#7]
Hey, thanks for this library! I am mostly using it to pack already downloaded/cleaned texts into EPUB format.

Is it possible to use a local image as cover?

**Comment by dfface** [comment]
Thanks for your feedback, I just released a new version (v2.5).

Features:
* add local resources support: just set `local` parameter in `create_chapter_*`  to `True`. See the [localfile2epub.py](https://github.com/dfface/xml2epub/tree/main/examples/localfile2epub) example for details.
* add local image cover support: for instance, just use `xml2epub.create_chapter_from_string("./local_file_example/03-06-OdnY0A.png", strict=False, local=True)`. See the [localfile2epub.py](https://github.com/dfface/xml2epub/tree/main/examples/localfile2epub) example for details.

Tips:
* If you want to add a cover image yourself, use the `create_chapter_from_string` method, then assign `html_string` to the image URL (e.g. `https://www.xxx.com/xxx.png`) and keep the `strict=False` parameter. Or assign `html_string` to the local image file path (e.g. `./xxx.png`) and keep the `local=True` and `strict=False` parameters.
* If the images and CSS files in your html are local resources, please set the `local` parameter in `create_chapter_*`  to `True`, then the program will automatically copy the local resources instead of getting them from the Internet.

**Comment by Zottelchen** [comment]
Thank you so much, it works great! The only minor issue is now that it still generates and adds a default `cover.jpg` to the archive (but it isn't shown, so it is fine).

**Comment by dfface** [comment]
Haha, that was indeed a problem, it has been fixed in v2.6.

**Comment by Zottelchen** [comment]
Thanks again!
